name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      # - name: Publish
      #   run: dotnet publish ChangeLog.csproj -c Release -o folderName
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: folderName
      #     path: ChangeLog/folderName/**
      #     if-no-files-found: error
